---
title: "Influence of Metheorogical Factors on Health"
author: "Alexey Grigorev"
date: "12/03/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(magrittr)
library(ggplot2)
library(xts)
```

## Reading the data

```{r}
default.par = par()
setwd("~/rproj/khb-mortality-analysis/data")

mort = 
  read.table("SSC_Mo.txt", sep='\t', header=T, dec=',') %>%
  filter(complete.cases(.)) %>%
  select(date=Date.1, mortality=Mo.W.M) %>%
  mutate(date=as.Date(date, format="%d.%m.%Y"))

mort.date = range(mort$date)

temp = 
  read.table("Khb_Temp_Daily.txt", sep=';', header=F, dec=',') %>% 
  filter(complete.cases(.)) %>%
  mutate(date=as.Date(ISOdate(V2, V3, V4))) %>%
  select(date, t.min=V6, t.mean=V8, t.max=V10) %>% 
  filter(date >= mort.date[1] & date <= mort.date[2])

press = read.table('Khb_press_dew_wind.txt', sep='\t', header=T, dec='.')
press = press %>% 
  mutate(date=as.Date(ISOdate(Year, Month, Day)),
         wind.speed=sqrt(uw * uw + vw * vw)) %>%
  select(date, pressure=P0, dew.point=Td, temp=Ta, wind.speed) %>% 
  group_by(date) %>%
  summarise(pressure.ampl=max(pressure, na.rm=T)-min(pressure, na.rm=T),
            pressure=mean(pressure, na.rm=T),
            dew.point.ampl=max(dew.point, na.rm=T)-min(dew.point, na.rm=T),
            dew.point=mean(dew.point, na.rm=T),
            wind.speed.max=max(wind.speed, na.rm=T),
            wind.speed.min=min(wind.speed, na.rm=T),
            wind.speed.ampl=wind.speed.max-wind.speed.min,
            wind.speed=mean(wind.speed, na.rm=T),
            t.min=min(temp, na.rm=T), 
            t.max=max(temp, na.rm=T),
            t.mean=round(mean(temp, na.rm=T), digits=3))

temp2 = press %>%
  select(date, t.min, t.mean, t.max) %>%
  filter(date > max(temp$date) & date <= mort.date[2])

temp = rbind(temp, temp2)

press = press %>%
  select(-c(t.min, t.mean, t.max))

temp = merge(temp, press, by='date')
merged = merge(mort, temp, by='date')
```

Some information about wind vectors: http://wx.gmu.edu/dev/clim301/lectures/wind/wind-uv.html


### Holidays


```{r}
wd = weekdays(merged$date, abbreviate=T)
wd = factor(wd, levels=c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"))
levels(wd) = 1:7

holidays = read.table("publicholidays-russia.txt") %>% 
  select(date=V1) %>% 
  mutate(date=as.Date(date, format="%d-%m-%Y"))

merged$is.holiday = merged$date %in% holidays$date
merged$date.dof = wd
merged$is.workday = wd %in% 1:5
```


###Extra Indicators 

Will calculate:

- `ET_M` Effective Temperature by Missenard
- `ET_S` Effective Temperature by Stedman 
- 

```{r}
merged$ET_S = 2.719 + 0.994 * merged$t.mean + 0.016 * merged$dew.point ** 2

ggplot(data=merged) + 
  geom_histogram(aes(x=ET_S, y=..density.., fill='ET_S'), 
                 binwidth=2.5, col='black', alpha=0.3) + 
  geom_density(aes(x=ET_S), col='black') +
  geom_histogram(aes(x=t.mean, y=..density.., fill='T'), 
                 binwidth=2.5, col='black',  alpha=0.3) + 
  geom_density(aes(x=t.mean), col='blue') +
  guides(fill=guide_legend(title='Temperature'))
  labs(x='Temperature', y='Count')
  

cut(tmp$ET_S, breaks=c(-Inf, 18, 23, 28, Inf))

```